name: Android debug build

on: 
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: subosito/flutter-action@v2
    - uses: actions/checkout@v3
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
