# This is a basic workflow to help you get started with Actions

name: publish web

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build web
    env:
      my_secret: ${{secrets.COMMIT_SECRET}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.0.5
          #channel: 'dev'

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git branch -m master main
          git config --global user.email truemaxdh@gmail.com
          git config --global user.name truemaxdh
          
          git status
          
          echo lets remote add origin
          git remote add origin https://truemaxdh:${{secrets.COMMIT_SECRET}}@github.com/truemaxdh/flutter_musicplayer.git
          
          echo lets checkout gh-pages
          git checkout -b gh-pages
          
          echo lets add --all
          git add --all
          
          echo lets commit -m "update"
          git commit -m "update"
          
          echo lets push origin gh-pages -f
          git push origin gh-pages -f
      
